import { Receipt } from 'lucide-react';
import { MenuModule } from '../types';

export const entradasNotaFiscal: MenuModule = {
  id: 'fiscal',
  tag_web: '04.00.00',
  label: "Entrada de NF's",
  icon: <Receipt size={18} />,
  subsections: [
    { title: "Principal", items: ['entrada_de_nf_s.dashboard'] },
    { title: "Documentos Fiscais", items: ['entrada_de_nf_s.nota_fiscal', 'entrada_de_nf_s.confronto_nfe', 'entrada_de_nf_s.confronto_nfse', 'entrada_de_nf_s.confronto_cte'] },
  ],
  funcionalidades: {
    'entrada_de_nf_s.nota_fiscal': {
      tag_web: '04.02.00',
      label: "Nota Fiscal Entrada",
      route: "/cpr/nota-fiscal",
      tela: '',  // TODO: codigo de menu do legado
      acoes: [
        { tag_web: '04.02.01', nome: "Editar Nota"  },
        { tag_web: '04.02.02', nome: "Pesquisar"  },
        { tag_web: '04.02.03', nome: "Inserir Item"  },
        { tag_web: '04.02.04', nome: "Alterar Item"  },
        { tag_web: '04.02.05', nome: "Excluir Item"  },
        { tag_web: '04.02.06', nome: "Cadastrar Novo Item"  },
        { tag_web: '04.02.07', nome: "Adicionar Item"  },
        { tag_web: '04.02.08', nome: "Inserir Imposto"  },
        { tag_web: '04.02.09', nome: "Salvar Imposto"  },
        { tag_web: '04.02.10', nome: "Excluir Imposto"  },
        { tag_web: '04.02.11', nome: "Limpar Imposto"  },
        { tag_web: '04.02.12', nome: "Inserir Departamento"  },
        { tag_web: '04.02.13', nome: "Alterar Departamento"  },
        { tag_web: '04.02.14', nome: "Excluir Departamento"  },
        { tag_web: '04.02.15', nome: "Inserir Financeiro"  },
        { tag_web: '04.02.16', nome: "Alterar Financeiro"  },
        { tag_web: '04.02.17', nome: "Excluir Financeiro"  },
        { tag_web: '04.02.18', nome: "Finalizar"  },
        { tag_web: '04.02.24', nome: "Importar NFe XML"  },
        { tag_web: '04.02.25', nome: "Importar NFSe XML"  },
        { tag_web: '04.02.19', nome: "Salvar"  },
        { tag_web: '04.02.20', nome: "Voltar"  },
        { tag_web: '04.02.21', nome: "Nota Compra Direta"  },
        { tag_web: '04.02.22', nome: "Nota de Pedido"  },
        { tag_web: '04.02.23', nome: "Recorrência"  },
        { tag_web: '04.02.26', nome: "Exportar NF-e XML"  },
        { tag_web: '04.02.27', nome: "Exportar Dados"  },
        { tag_web: '04.02.28', nome: "Visualizar"  },
        { tag_web: '04.02.29', nome: "Criar"  },
        { tag_web: '04.02.30', nome: "Excluir"  },
        { tag_web: '04.02.31', nome: "Imprimir"  },
      ],
    },
    'entrada_de_nf_s.confronto_nfe': {
      tag_web: '04.03.00',
      label: "Confronto NF-e",
      route: "/cpr/confronto-nfe",
      tela: '',  // TODO: codigo de menu do legado
      acoes: [
        { tag_web: '04.03.01', nome: "Importar NF-e SEFAZ"  },
        { tag_web: '04.03.02', nome: "Baixar NF-e"  },
        { tag_web: '04.03.03', nome: "Baixar NF-e por Chave"  },
        { tag_web: '04.03.04', nome: "Baixar"  },
        { tag_web: '04.03.05', nome: "Consultar"  },
        { tag_web: '04.03.06', nome: "Visualizar"  },
        { tag_web: '04.03.07', nome: "Criar"  },
        { tag_web: '04.03.08', nome: "Editar"  },
        { tag_web: '04.03.09', nome: "Excluir"  },
        { tag_web: '04.03.10', nome: "Imprimir"  },
        { tag_web: '04.03.11', nome: "Exportar"  },
        { tag_web: '04.03.12', nome: "Pesquisar"  },
      ],
    },
    'entrada_de_nf_s.confronto_nfse': {
      tag_web: '04.04.00',
      label: "Confronto NFS-e",
      route: "/cpr/confronto-nfse",
      tela: '',  // TODO: codigo de menu do legado
      acoes: [
        { tag_web: '04.04.01', nome: "Importar SEFAZ"  },
        { tag_web: '04.04.02', nome: "Baixar"  },
        { tag_web: '04.04.03', nome: "Consultar"  },
        { tag_web: '04.04.04', nome: "Baixar NFS-e"  },
        { tag_web: '04.04.05', nome: "Baixar NFS-e por Chave"  },
        { tag_web: '04.04.06', nome: "Visualizar"  },
        { tag_web: '04.04.07', nome: "Criar"  },
        { tag_web: '04.04.08', nome: "Editar"  },
        { tag_web: '04.04.09', nome: "Excluir"  },
        { tag_web: '04.04.10', nome: "Imprimir"  },
        { tag_web: '04.04.11', nome: "Exportar"  },
        { tag_web: '04.04.12', nome: "Pesquisar"  },
      ],
    },
    'entrada_de_nf_s.confronto_cte': {
      tag_web: '04.06.00',
      label: "Confronto CT-e",
      route: "/cpr/confronto-cte",
      tela: '',
      acoes: [
        { tag_web: '04.06.01', nome: "Importar CT-e SEFAZ"  },
        { tag_web: '04.06.02', nome: "Baixar CT-e"  },
        { tag_web: '04.06.03', nome: "Baixar CT-e por Chave"  },
        { tag_web: '04.06.04', nome: "Consultar"  },
        { tag_web: '04.06.05', nome: "Visualizar"  },
        { tag_web: '04.06.06', nome: "Criar"  },
        { tag_web: '04.06.07', nome: "Editar"  },
        { tag_web: '04.06.08', nome: "Excluir"  },
        { tag_web: '04.06.09', nome: "Imprimir"  },
        { tag_web: '04.06.10', nome: "Exportar"  },
        { tag_web: '04.06.11', nome: "Pesquisar"  },
      ],
    },
    'entrada_de_nf_s.dashboard': {
      tag_web: '04.01.00',
      label: "Dashboard",
      route: null,
      tela: '',  // TODO
    },
  },
};
